

const TOOLS = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single file",
    icon: "layers",
    color: "indigo",
    endpoint: "/api/merge",
    multiple: true,
    accept: ".pdf",
    acceptLabel: "PDF files (max 5)",
    minFiles: 2,
    maxFiles: 5,
    reorderable: true,
    options: [],
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Select which pages to keep or remove",
    icon: "scissors",
    color: "pink",
    endpoint: "/api/split",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    pageSelector: true,
    options: [],
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce PDF file size without losing quality",
    icon: "archive",
    color: "green",
    endpoint: "/api/compress",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [
      {
        id: "quality",
        label: "Compression Level",
        type: "radio",
        choices: [
          { value: "high", label: "Low" },
          { value: "medium", label: "Medium" },
          { value: "low", label: "Maximum" },
        ],
        default: "medium",
      },
    ],
  },
  {
    id: "extract-text",
    name: "Extract Text",
    description: "Extract all text content from PDF pages",
    icon: "text-select",
    color: "blue",
    endpoint: "/api/convert/extract-text",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [],
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Convert PDF pages to JPG or PNG images",
    icon: "image",
    color: "cyan",
    endpoint: "/api/convert/pdf-to-image",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [
      {
        id: "fmt",
        label: "Image Format",
        type: "radio",
        choices: [
          { value: "png", label: "PNG" },
          { value: "jpg", label: "JPG" },
        ],
        default: "png",
      },
      {
        id: "dpi",
        label: "Quality (DPI)",
        type: "radio",
        choices: [
          { value: "150", label: "150 DPI" },
          { value: "200", label: "200 DPI" },
          { value: "300", label: "300 DPI" },
        ],
        default: "200",
      },
    ],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Convert images into a single PDF document",
    icon: "file-plus",
    color: "orange",
    endpoint: "/api/convert/image-to-pdf",
    multiple: true,
    accept: ".jpg,.jpeg,.png,.bmp,.gif,.tiff,.webp",
    acceptLabel: "Image files",
    options: [
      {
        id: "page_size",
        label: "Page Size",
        type: "radio",
        choices: [
          { value: "a4", label: "A4" },
          { value: "letter", label: "Letter" },
        ],
        default: "a4",
      },
    ],
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents to PDF format",
    icon: "file-check",
    color: "blue",
    endpoint: "/api/convert/word-to-pdf",
    multiple: false,
    accept: ".doc,.docx",
    acceptLabel: "Word document",
    options: [],
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Add text watermarks to your PDF pages",
    icon: "droplets",
    color: "cyan",
    endpoint: "/api/watermark",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    livePreview: "watermark",
    options: [
      {
        id: "text",
        label: "Watermark Text",
        type: "text",
        placeholder: "Enter watermark text",
        default: "CONFIDENTIAL",
        required: true,
      },
      {
        id: "opacity",
        label: "Opacity",
        type: "range",
        min: 0.1,
        max: 1,
        step: 0.1,
        default: 0.3,
      },
      {
        id: "font_size",
        label: "Font Size",
        type: "number",
        min: 10,
        max: 200,
        default: 50,
      },
      {
        id: "rotation",
        label: "Rotation (degrees)",
        type: "radio",
        choices: [
          { value: "0", label: "0°" },
          { value: "45", label: "45°" },
          { value: "90", label: "90°" },
        ],
        default: "45",
      },
    ],
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate all pages by 90°, 180° or 270°",
    icon: "rotate-cw",
    color: "orange",
    endpoint: "/api/rotate",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    livePreview: "rotate",
    options: [
      {
        id: "rotation",
        label: "Rotation",
        type: "radio",
        choices: [
          { value: "90", label: "90°" },
          { value: "180", label: "180°" },
          { value: "270", label: "270°" },
        ],
        default: "90",
      },
    ],
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt your PDF with a password",
    icon: "lock",
    color: "red",
    endpoint: "/api/protect",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [
      {
        id: "password",
        label: "Password",
        type: "password",
        placeholder: "Enter password",
        required: true,
      },
    ],
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF",
    icon: "unlock",
    color: "green",
    endpoint: "/api/unlock",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [
      {
        id: "password",
        label: "Current Password",
        type: "password",
        placeholder: "Enter current password",
        required: true,
      },
    ],
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    description: "Add page numbers to your PDF document",
    icon: "hash",
    color: "red",
    endpoint: "/api/page-numbers",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [
      {
        id: "position",
        label: "Number Position",
        type: "select",
        choices: [
          { value: "bottom-center", label: "Bottom Center" },
          { value: "bottom-left", label: "Bottom Left" },
          { value: "bottom-right", label: "Bottom Right" },
          { value: "top-center", label: "Top Center" },
          { value: "top-left", label: "Top Left" },
          { value: "top-right", label: "Top Right" },
        ],
        default: "bottom-center",
      },
      {
        id: "start_number",
        label: "Start Number",
        type: "number",
        min: 1,
        max: 9999,
        default: 1,
      },
      {
        id: "font_size",
        label: "Font Size",
        type: "number",
        min: 8,
        max: 36,
        default: 12,
      },
    ],
  },
  {
    id: "ppt-to-pdf",
    name: "PPT to PDF",
    description: "Convert PowerPoint presentations to PDF",
    icon: "presentation",
    color: "orange",
    endpoint: "/api/convert/ppt-to-pdf",
    multiple: false,
    accept: ".ppt,.pptx,.odp",
    acceptLabel: "PowerPoint file",
    options: [],
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF",
    icon: "table",
    color: "green",
    endpoint: "/api/convert/excel-to-pdf",
    multiple: false,
    accept: ".xls,.xlsx,.ods,.csv",
    acceptLabel: "Spreadsheet file",
    options: [],
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Convert HTML web pages to PDF documents",
    icon: "code",
    color: "cyan",
    endpoint: "/api/convert/html-to-pdf",
    multiple: false,
    accept: ".html,.htm",
    acceptLabel: "HTML file",
    options: [],
  },
  {
    id: "url-to-pdf",
    name: "URL to PDF",
    description: "Convert a web page URL to a PDF document",
    icon: "globe",
    color: "teal",
    endpoint: "/api/convert/url-to-pdf",
    multiple: false,
    requiresUpload: false,
    options: [
      {
        id: "url",
        label: "Web Page URL",
        type: "url",
        placeholder: "https://example.com",
        required: true,
      },
    ],
  },
  {
    id: "filter",
    name: "Filter PDF",
    description: "Apply visual filters like grayscale or invert to your PDF",
    icon: "sliders",
    color: "gold",
    endpoint: "/api/filter",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    livePreview: "filter",
    options: [
      {
        id: "filter_type",
        label: "Filter Type",
        type: "radio",
        choices: [
          { value: "grayscale", label: "Grayscale" },
          { value: "invert", label: "Invert" },
          { value: "brighter", label: "Brighter" },
          { value: "darker", label: "Darker" },
        ],
        default: "grayscale",
      },
    ],
  },
  {
    id: "flatten",
    name: "Flatten PDF",
    description: "Consolidate all layers, annotations, and form fields into a single flattened layer",
    icon: "layers",
    color: "indigo",
    endpoint: "/api/flatten",
    multiple: false,
    accept: ".pdf",
    acceptLabel: "PDF file",
    options: [],
  },
];

window.TOOLS = TOOLS;
